title: My Plugins Library
description: A collection of freeware plugins and addons
baseurl: ""
url: ""
collections:
  plugins:
    output: true
    permalink: /plugins/:slug/
  countries:
    output: true
    permalink: /countries/:slug/
paginate: 10
